server:
  port: 8080

spring:
  security:
    user:
      name: admin
      password: 1234
  datasource:
    url: jdbc:postgresql://localhost:5432/obaju-ecommerce
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 200MB

spring-doc:
  swagger-ui:
    path: swagger-ui.html
    operationsSorter: method

file:
  upload-dir: src/main/resources/upload-dir